ARG BASE_IMAGE=dartsim/dart-dev:manylinux_2_28_aarch64-min-v7.0
FROM $BASE_IMAGE

ARG NUM_CORES=14

# Missing optional dependencies:
#   bullet
#   ipopt
#   nlopt
#   spdlog

# openscenegraph
RUN git clone https://github.com/openscenegraph/OpenSceneGraph.git \
    && mkdir -p OpenSceneGraph/build \
    && cmake OpenSceneGraph -B OpenSceneGraph/build -DCMAKE_BUILD_TYPE=Release -DBUILD_OSG_APPLICATIONS=OFF \
    && cmake --build OpenSceneGraph/build --target install -j${NUM_CORES} \
    && rm -rf OpenSceneGraph
