ARG BASE_IMAGE=dartsim/dart-dev:manylinux2014_ppc64le-min-v7.0
FROM $BASE_IMAGE

ARG NUM_CORES=14

# Missing optional dependencies:
#   ipopt
#   nlopt
#   spdlog

# Bullet
RUN git clone https://github.com/bulletphysics/bullet3.git -b 3.25 \
    && mkdir -p bullet3/build \
    && cmake bullet3 -B bullet3/build -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIT_TESTS=OFF -DBUILD_CPU_DEMOS=OFF \
    && cmake --build bullet3/build --target install -j${NUM_CORES} \
    && rm -rf bullet3

# openscenegraph
RUN git clone https://github.com/openscenegraph/OpenSceneGraph.git \
    && mkdir -p OpenSceneGraph/build \
    && cmake OpenSceneGraph -B OpenSceneGraph/build -DCMAKE_BUILD_TYPE=Release -DBUILD_OSG_APPLICATIONS=OFF \
    && cmake --build OpenSceneGraph/build --target install -j${NUM_CORES} \
    && rm -rf OpenSceneGraph
