# GitHub Actions: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Build and push Docker images Action: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish Docker image

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    # Run at 02:00 UTC every day
    - cron: "0 2 * * 0-6"

env:
  DOCKER_REPO: dartsim/dart-dev # https://hub.docker.com/repository/docker/dartsim/dart-dev

jobs:
  xenial-32bit-v6_10:
    name: xenial-32bit-v6.10
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: i386/ubuntu
      UBUNTU_VERSION: xenial
      DART_VERSION: v6.10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          build-args: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            BASE_DIR=./${{ env.DART_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-32bit-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  xenial-v6_10:
    name: xenial-v6.10
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: xenial
      DART_VERSION: v6.10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            BASE_DIR=./${{ env.DART_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  bionic-v6_10:
    name: bionic-v6.10
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: bionic
      DART_VERSION: v6.10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            BASE_DIR=./${{ env.DART_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  focal-v6_10:
    name: focal-v6.10
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: focal
      DART_VERSION: v6.10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            BASE_DIR=./${{ env.DART_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  groovy-v6_10:
    name: groovy-v6.10
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: groovy
      DART_VERSION: v6.10
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          build-args: |
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}
            BASE_DIR=./${{ env.DART_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
