# GitHub Actions: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Build and push Docker images Action: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish Docker image

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    # Run at 02:00 UTC every Friday
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron: "0 2 * * FRI"

env:
  DOCKER_REPO: dartsim/dart-dev # https://hub.docker.com/repository/docker/dartsim/dart-dev

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [bionic, focal, hirsute]
        dart_version: [v6.10, v7.0, v8.0]
        include:
          - distro: xenial
            dart_version: v6.10
    env:
      UBUNTU_VERSION: ${{ matrix.distro }}
      DART_VERSION: ${{ matrix.dart_version }}
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile.ubuntu.${{ env.UBUNTU_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ env.DOCKER_REPO }}:ubuntu-${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # Xenial 32bit on i386
  xenial-32bit-v6_10:
    name: xenial-32bit-v6.10
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: xenial
      DART_VERSION: v6.10
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile.ubuntu.xenial.32bit
          push: true
          tags: ${{ env.DOCKER_REPO }}:ubuntu-${{ env.UBUNTU_VERSION }}-32bit-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # Bionic image for API documentation builds
  bionic-docs:
    name: bionic-docs
    runs-on: ubuntu-latest
    env:
      UBUNTU_VERSION: bionic
      DART_VERSION: docs
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # Archlinux on amd64
  archlinux:
    name: archlinux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dart_version: [v7.0, v8.0]
    env:
      DART_VERSION: ${{ matrix.dart_version }}
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.DART_VERSION }}/Dockerfile.archlinux
          push: true
          tags: ${{ env.DOCKER_REPO }}:archlinux-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
